In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\basitsachinwala\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\basitsachinwala\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\basitsachinwala\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.2-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/11.0 MB 4.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.0 MB 4.5 MB/s eta 0:00:02
   ----------- ---------------------------- 3.1/11.0 MB 4.4 MB/s eta 0:00:02
   --------------- ------------------------ 4.2/11.0 MB 4.5 MB/s eta 0:00:02
   ------------------- -------------------- 5.2/11.0 MB 4.6 MB/s eta 0:00:02
   ---------------------- ----------------- 6.3/11.0 MB 4.7 MB/s eta 0:00:02
   -------------------------- ------------- 7.3/11.0 MB 4.6 MB/s eta 0:00:01
   ------------------------------ --------- 8.4/11.0 MB 4.7 MB/s eta 0:00:01
   ---------------------------------- ----- 9.4/11.0 MB 4.7 MB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 4.7 MB/s  0:00:02
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed pandas-2.3.2 pytz-2025.2 tzdata-2025.2

In [3]:
import pandas as pd

In [4]:
my_data = [10,20,30]
labels = ['a','b','c']

In [5]:
pd.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
d = {'a' : 10 , 'b' : 20 , 'c' : 30}

In [7]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [8]:
data_frame = pd.Series(['UK','USA','IND'],[1,2,3])

In [9]:
data_frame

1     UK
2    USA
3    IND
dtype: object

In [11]:
data_frame[1]

'UK'

In [12]:
sre1 = pd.Series([1,2,3,4,5],['a','b','c','d','e'])
sre2 = pd.Series([1,2,3,4,5],['a','b','c','d','e'])

sre1 - sre2

a    0
b    0
c    0
d    0
e    0
dtype: int64

In [13]:
sre1 = pd.Series([1,2,3,4,5],['a','b','c','d','e'])
sre2 = pd.Series([1,2,3,4,5],['a','b','c','D','e'])

sre1 - sre2

D    NaN
a    0.0
b    0.0
c    0.0
d    NaN
e    0.0
dtype: float64

In [15]:
import numpy as np

In [18]:
from numpy.random import randn

In [16]:
np.random.seed(101)

In [24]:
df = pd.DataFrame(randn(5,4),['X','Y','Z','U','V'],['A','B','C','D'])

In [25]:
df

          A         B         C         D
X  1.606780 -1.115710 -1.385379 -1.329660
Y  0.041460 -0.411055 -0.771329  0.110477
Z -0.804652  0.253548  0.649148  0.358941
U -1.080471  0.902398  0.161781  0.833029
V  0.975720 -0.388239  0.783316 -0.708954

In [26]:
df['A']

X    1.606780
Y    0.041460
Z   -0.804652
U   -1.080471
V    0.975720
Name: A, dtype: float64

In [27]:
type(df)

pandas.core.frame.DataFrame

In [28]:
type(df['A'])

pandas.core.series.Series

In [29]:
df[['A','D']]

          A         D
X  1.606780 -1.329660
Y  0.041460  0.110477
Z -0.804652  0.358941
U -1.080471  0.833029
V  0.975720 -0.708954

In [31]:
df['new'] = df['A'] + df['D']

In [32]:
df

          A         B         C         D       new
X  1.606780 -1.115710 -1.385379 -1.329660  0.277120
Y  0.041460 -0.411055 -0.771329  0.110477  0.151937
Z -0.804652  0.253548  0.649148  0.358941 -0.445711
U -1.080471  0.902398  0.161781  0.833029 -0.247442
V  0.975720 -0.388239  0.783316 -0.708954  0.266766

In [35]:
df.drop('new', axis = 1)

          A         B         C         D
X  1.606780 -1.115710 -1.385379 -1.329660
Y  0.041460 -0.411055 -0.771329  0.110477
Z -0.804652  0.253548  0.649148  0.358941
U -1.080471  0.902398  0.161781  0.833029
V  0.975720 -0.388239  0.783316 -0.708954

In [36]:
df

          A         B         C         D       new
X  1.606780 -1.115710 -1.385379 -1.329660  0.277120
Y  0.041460 -0.411055 -0.771329  0.110477  0.151937
Z -0.804652  0.253548  0.649148  0.358941 -0.445711
U -1.080471  0.902398  0.161781  0.833029 -0.247442
V  0.975720 -0.388239  0.783316 -0.708954  0.266766

In [37]:
df.drop('new', axis = 1,inplace=True)

In [38]:
df

          A         B         C         D
X  1.606780 -1.115710 -1.385379 -1.329660
Y  0.041460 -0.411055 -0.771329  0.110477
Z -0.804652  0.253548  0.649148  0.358941
U -1.080471  0.902398  0.161781  0.833029
V  0.975720 -0.388239  0.783316 -0.708954

In [42]:
df.loc['X']

A    1.606780
B   -1.115710
C   -1.385379
D   -1.329660
Name: X, dtype: float64

In [43]:
df.iloc[0]

A    1.606780
B   -1.115710
C   -1.385379
D   -1.329660
Name: X, dtype: float64

In [44]:
df.loc[['X','Y'],['A','B']]

         A         B
X  1.60678 -1.115710
Y  0.04146 -0.411055

In [46]:
df.iloc[:2,:2]

         A         B
X  1.60678 -1.115710
Y  0.04146 -0.411055

In [47]:
df>0

       A      B      C      D
X   True  False  False  False
Y   True  False  False   True
Z  False   True   True   True
U  False   True   True   True
V   True  False   True  False

In [48]:
df[df>0]

         A         B         C         D
X  1.60678       NaN       NaN       NaN
Y  0.04146       NaN       NaN  0.110477
Z      NaN  0.253548  0.649148  0.358941
U      NaN  0.902398  0.161781  0.833029
V  0.97572       NaN  0.783316       NaN

In [49]:
df[df['A']>0]

         A         B         C         D
X  1.60678 -1.115710 -1.385379 -1.329660
Y  0.04146 -0.411055 -0.771329  0.110477
V  0.97572 -0.388239  0.783316 -0.708954

In [50]:
resultdf = df[df['A'] < 0]

In [51]:
resultdf['B']

Z    0.253548
U    0.902398
Name: B, dtype: float64

In [52]:
df[df['A'] < 0]['B']

Z    0.253548
U    0.902398
Name: B, dtype: float64

In [58]:
df[(df['A']>0) | (df['B']>1)]

         A         B         C         D
X  1.60678 -1.115710 -1.385379 -1.329660
Y  0.04146 -0.411055 -0.771329  0.110477
V  0.97572 -0.388239  0.783316 -0.708954

In [59]:
df.reset_index()

  index         A         B         C         D
0     X  1.606780 -1.115710 -1.385379 -1.329660
1     Y  0.041460 -0.411055 -0.771329  0.110477
2     Z -0.804652  0.253548  0.649148  0.358941
3     U -1.080471  0.902398  0.161781  0.833029
4     V  0.975720 -0.388239  0.783316 -0.708954

In [60]:
df

          A         B         C         D
X  1.606780 -1.115710 -1.385379 -1.329660
Y  0.041460 -0.411055 -0.771329  0.110477
Z -0.804652  0.253548  0.649148  0.358941
U -1.080471  0.902398  0.161781  0.833029
V  0.975720 -0.388239  0.783316 -0.708954

In [61]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [62]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [65]:
df = pd.DataFrame(np.random.rand(6,2),hier_index,['A','B'])

In [66]:
df

             A         B
G1 1  0.045510  0.885041
   2  0.276421  0.580924
   3  0.910662  0.992591
G2 1  0.062224  0.928481
   2  0.517161  0.945382
   3  0.546931  0.264162

In [68]:
df['Sum'] = df['A'] + df['B']
df.set_index('Sum')

                 A         B
Sum
0.930551  0.045510  0.885041
0.857346  0.276421  0.580924
1.903253  0.910662  0.992591
0.990705  0.062224  0.928481
1.462543  0.517161  0.945382
0.811093  0.546931  0.264162