In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\basitsachinwala\appdata\local\programs\python\python313\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\basitsachinwala\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\basitsachinwala\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\basitsachinwala\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\basitsachinwala\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\basitsachinwala\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
my_data = [10,20,30]
labels = ['a','b','c']

In [5]:
pd.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
d = {'a' : 10 , 'b' : 20 , 'c' : 30}

In [7]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [8]:
data_frame = pd.Series(['UK','USA','IND'],[1,2,3])

In [9]:
data_frame

1     UK
2    USA
3    IND
dtype: object

In [11]:
data_frame[1]

'UK'

In [12]:
sre1 = pd.Series([1,2,3,4,5],['a','b','c','d','e'])
sre2 = pd.Series([1,2,3,4,5],['a','b','c','d','e'])

sre1 - sre2

a    0
b    0
c    0
d    0
e    0
dtype: int64

In [13]:
sre1 = pd.Series([1,2,3,4,5],['a','b','c','d','e'])
sre2 = pd.Series([1,2,3,4,5],['a','b','c','D','e'])

sre1 - sre2

D    NaN
a    0.0
b    0.0
c    0.0
d    NaN
e    0.0
dtype: float64

In [15]:
import numpy as np

In [18]:
from numpy.random import randn

In [16]:
np.random.seed(101)

In [24]:
df = pd.DataFrame(randn(5,4),['X','Y','Z','U','V'],['A','B','C','D'])

In [25]:
df

          A         B         C         D
X  1.606780 -1.115710 -1.385379 -1.329660
Y  0.041460 -0.411055 -0.771329  0.110477
Z -0.804652  0.253548  0.649148  0.358941
U -1.080471  0.902398  0.161781  0.833029
V  0.975720 -0.388239  0.783316 -0.708954

In [26]:
df['A']

X    1.606780
Y    0.041460
Z   -0.804652
U   -1.080471
V    0.975720
Name: A, dtype: float64

In [27]:
type(df)

pandas.core.frame.DataFrame

In [28]:
type(df['A'])

pandas.core.series.Series

In [29]:
df[['A','D']]

          A         D
X  1.606780 -1.329660
Y  0.041460  0.110477
Z -0.804652  0.358941
U -1.080471  0.833029
V  0.975720 -0.708954

In [31]:
df['new'] = df['A'] + df['D']

In [32]:
df

          A         B         C         D       new
X  1.606780 -1.115710 -1.385379 -1.329660  0.277120
Y  0.041460 -0.411055 -0.771329  0.110477  0.151937
Z -0.804652  0.253548  0.649148  0.358941 -0.445711
U -1.080471  0.902398  0.161781  0.833029 -0.247442
V  0.975720 -0.388239  0.783316 -0.708954  0.266766

In [35]:
df.drop('new', axis = 1)

          A         B         C         D
X  1.606780 -1.115710 -1.385379 -1.329660
Y  0.041460 -0.411055 -0.771329  0.110477
Z -0.804652  0.253548  0.649148  0.358941
U -1.080471  0.902398  0.161781  0.833029
V  0.975720 -0.388239  0.783316 -0.708954

In [36]:
df

          A         B         C         D       new
X  1.606780 -1.115710 -1.385379 -1.329660  0.277120
Y  0.041460 -0.411055 -0.771329  0.110477  0.151937
Z -0.804652  0.253548  0.649148  0.358941 -0.445711
U -1.080471  0.902398  0.161781  0.833029 -0.247442
V  0.975720 -0.388239  0.783316 -0.708954  0.266766

In [37]:
df.drop('new', axis = 1,inplace=True)

In [38]:
df

          A         B         C         D
X  1.606780 -1.115710 -1.385379 -1.329660
Y  0.041460 -0.411055 -0.771329  0.110477
Z -0.804652  0.253548  0.649148  0.358941
U -1.080471  0.902398  0.161781  0.833029
V  0.975720 -0.388239  0.783316 -0.708954

In [42]:
df.loc['X']

A    1.606780
B   -1.115710
C   -1.385379
D   -1.329660
Name: X, dtype: float64

In [43]:
df.iloc[0]

A    1.606780
B   -1.115710
C   -1.385379
D   -1.329660
Name: X, dtype: float64

In [44]:
df.loc[['X','Y'],['A','B']]

         A         B
X  1.60678 -1.115710
Y  0.04146 -0.411055

In [46]:
df.iloc[:2,:2]

         A         B
X  1.60678 -1.115710
Y  0.04146 -0.411055

In [47]:
df>0

       A      B      C      D
X   True  False  False  False
Y   True  False  False   True
Z  False   True   True   True
U  False   True   True   True
V   True  False   True  False

In [48]:
df[df>0]

         A         B         C         D
X  1.60678       NaN       NaN       NaN
Y  0.04146       NaN       NaN  0.110477
Z      NaN  0.253548  0.649148  0.358941
U      NaN  0.902398  0.161781  0.833029
V  0.97572       NaN  0.783316       NaN

In [49]:
df[df['A']>0]

         A         B         C         D
X  1.60678 -1.115710 -1.385379 -1.329660
Y  0.04146 -0.411055 -0.771329  0.110477
V  0.97572 -0.388239  0.783316 -0.708954

In [50]:
resultdf = df[df['A'] < 0]

In [51]:
resultdf['B']

Z    0.253548
U    0.902398
Name: B, dtype: float64

In [52]:
df[df['A'] < 0]['B']

Z    0.253548
U    0.902398
Name: B, dtype: float64

In [58]:
df[(df['A']>0) | (df['B']>1)]

         A         B         C         D
X  1.60678 -1.115710 -1.385379 -1.329660
Y  0.04146 -0.411055 -0.771329  0.110477
V  0.97572 -0.388239  0.783316 -0.708954

In [59]:
df.reset_index()

  index         A         B         C         D
0     X  1.606780 -1.115710 -1.385379 -1.329660
1     Y  0.041460 -0.411055 -0.771329  0.110477
2     Z -0.804652  0.253548  0.649148  0.358941
3     U -1.080471  0.902398  0.161781  0.833029
4     V  0.975720 -0.388239  0.783316 -0.708954

In [60]:
df

          A         B         C         D
X  1.606780 -1.115710 -1.385379 -1.329660
Y  0.041460 -0.411055 -0.771329  0.110477
Z -0.804652  0.253548  0.649148  0.358941
U -1.080471  0.902398  0.161781  0.833029
V  0.975720 -0.388239  0.783316 -0.708954

In [61]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [62]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [65]:
df = pd.DataFrame(np.random.rand(6,2),hier_index,['A','B'])

In [66]:
df

             A         B
G1 1  0.045510  0.885041
   2  0.276421  0.580924
   3  0.910662  0.992591
G2 1  0.062224  0.928481
   2  0.517161  0.945382
   3  0.546931  0.264162

In [68]:
df['Sum'] = df['A'] + df['B']
df.set_index('Sum')

                 A         B
Sum
0.930551  0.045510  0.885041
0.857346  0.276421  0.580924
1.903253  0.910662  0.992591
0.990705  0.062224  0.928481
1.462543  0.517161  0.945382
0.811093  0.546931  0.264162

In [5]:
import numpy as np

In [9]:
d = { 'A' : [1,2,np.nan] , 'B' : [1,np.nan,np.nan] , 'C' : [1,2,3]}

In [10]:
df = pd.DataFrame(d)

In [11]:
df

     A    B  C
0  1.0  1.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [12]:
df.dropna()

     A    B  C
0  1.0  1.0  1

In [13]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [17]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [18]:
df.dropna(thresh=2)

     A    B  C
0  1.0  1.0  1
1  2.0  NaN  2

In [23]:
m1=pd.DataFrame({
    "id" : [1,2,3],
    "name" : ['X','Y','Z']
})

m2=pd.DataFrame({
    "id" : [1,2,4],
    "age" : [22,25,12]
})

In [24]:
result = pd.merge(m1,m2,on="id",how="left")

In [25]:
result

   id name   age
0   1    X  22.0
1   2    Y  25.0
2   3    Z   NaN

In [26]:
concated = pd.concat([m1,m2] , axis=0)

In [27]:
concated

   id name   age
0   1    X   NaN
1   2    Y   NaN
2   3    Z   NaN
0   1  NaN  22.0
1   2  NaN  25.0
2   4  NaN  12.0

In [28]:
concated_col = pd.concat([m1,m2] , axis=1)

In [29]:
concated_col

   id name  id  age
0   1    X   1   22
1   2    Y   2   25
2   3    Z   4   12

In [30]:
import pandas as pd
import numpy as np

# reproducibility
np.random.seed(42)

# create sample dataset
data = pd.DataFrame({
    "CustomerID": np.random.randint(1001, 1010, size=20),
    "Region": np.random.choice(["North", "South", "East", "West"], size=20),
    "Product": np.random.choice(["Laptop", "Mobile", "Tablet", "Headphones"], size=20),
    "Quantity": np.random.randint(1, 5, size=20),
    "Price": np.random.randint(100, 1000, size=20),
    "PurchaseDate": pd.date_range("2025-01-01", periods=20, freq="D")
})

print(data)

    CustomerID Region     Product  Quantity  Price PurchaseDate
0         1007  North      Mobile         2    487   2025-01-01
1         1004   West      Tablet         1    101   2025-01-02
2         1008  South  Headphones         2    489   2025-01-03
3         1005  South      Tablet         1    665   2025-01-04
4         1007  North  Headphones         2    205   2025-01-05
5         1003   West  Headphones         4    871   2025-01-06
6         1007  North      Laptop         4    921   2025-01-07
7         1008  North      Tablet         3    576   2025-01-08
8         1005   East      Laptop         4    802   2025-01-09
9         1004   East      Tablet         3    501   2025-01-10
10        1008   East      Tablet         4    829   2025-01-11
11        1008  South      Laptop         1    655   2025-01-12
12        1003   West      Laptop         4    261   2025-01-13
13        1006   West      Tablet         3    301   2025-01-14
14        1005   West      Mobile         3    369   2025-01-15
15        1002   West  Headphones         2    962   2025-01-16
16        1008   East      Laptop         1    915   2025-01-17
17        1006  South  Headphones         4    370   2025-01-18
18        1002  South      Mobile         2    555   2025-01-19
19        1005   East      Mobile         4    561   2025-01-20

In [35]:
data.groupby('Product')['Price'].sum()

Product
Headphones    2897
Laptop        3554
Mobile        1972
Tablet        2973
Name: Price, dtype: int32

In [39]:
print(data.groupby('Region')['Quantity'].sum().min())

10

In [43]:
data.groupby('CustomerID').describe().transpose()

CustomerID                         1002                 1003  \
Quantity     count                  2.0                  2.0
             mean                   2.0                  4.0
             min                    2.0                  4.0
             25%                    2.0                  4.0
             50%                    2.0                  4.0
             75%                    2.0                  4.0
             max                    2.0                  4.0
             std                    0.0                  0.0
Price        count                  2.0                  2.0
             mean                 758.5                566.0
             min                  555.0                261.0
             25%                 656.75                413.5
             50%                  758.5                566.0
             75%                 860.25                718.5
             max                  962.0                871.0
             std              287.79246           431.335137
PurchaseDate count                    2                    2
             mean   2025-01-17 12:00:00  2025-01-09 12:00:00
             min    2025-01-16 00:00:00  2025-01-06 00:00:00
             25%    2025-01-16 18:00:00  2025-01-07 18:00:00
             50%    2025-01-17 12:00:00  2025-01-09 12:00:00
             75%    2025-01-18 06:00:00  2025-01-11 06:00:00
             max    2025-01-19 00:00:00  2025-01-13 00:00:00
             std                    NaN                  NaN

CustomerID                         1004                 1005  \
Quantity     count                  2.0                  4.0
             mean                   2.0                  3.0
             min                    1.0                  1.0
             25%                    1.5                  2.5
             50%                    2.0                  3.5
             75%                    2.5                  4.0
             max                    3.0                  4.0
             std               1.414214             1.414214
Price        count                  2.0                  4.0
             mean                 301.0               599.25
             min                  101.0                369.0
             25%                  201.0                513.0
             50%                  301.0                613.0
             75%                  401.0               699.25
             max                  501.0                802.0
             std             282.842712           182.490867
PurchaseDate count                    2                    4
             mean   2025-01-06 00:00:00  2025-01-12 00:00:00
             min    2025-01-02 00:00:00  2025-01-04 00:00:00
             25%    2025-01-04 00:00:00  2025-01-07 18:00:00
             50%    2025-01-06 00:00:00  2025-01-12 00:00:00
             75%    2025-01-08 00:00:00  2025-01-16 06:00:00
             max    2025-01-10 00:00:00  2025-01-20 00:00:00
             std                    NaN                  NaN

CustomerID                         1006                 1007  \
Quantity     count                  2.0                  3.0
             mean                   3.5             2.666667
             min                    3.0                  2.0
             25%                   3.25                  2.0
             50%                    3.5                  2.0
             75%                   3.75                  3.0
             max                    4.0                  4.0
             std               0.707107             1.154701
Price        count                  2.0                  3.0
             mean                 335.5           537.666667
             min                  301.0                205.0
             25%                 318.25                346.0
             50%                  335.5                487.0
             75%                 352.75                704.0
             max                  370.0                921.0
             std              48.790368           360.678989
PurchaseDate count                    2                    3
             mean   2025-01-16 00:00:00  2025-01-04 08:00:00
             min    2025-01-14 00:00:00  2025-01-01 00:00:00
             25%    2025-01-15 00:00:00  2025-01-03 00:00:00
             50%    2025-01-16 00:00:00  2025-01-05 00:00:00
             75%    2025-01-17 00:00:00  2025-01-06 00:00:00
             max    2025-01-18 00:00:00  2025-01-07 00:00:00
             std                    NaN                  NaN

CustomerID                         1008
Quantity     count                  5.0
             mean                   2.2
             min                    1.0
             25%                    1.0
             50%                    2.0
             75%                    3.0
             max                    4.0
             std                1.30384
Price        count                  5.0
             mean                 692.8
             min                  489.0
             25%                  576.0
             50%                  655.0
             75%                  829.0
             max                  915.0
             std             176.443192
PurchaseDate count                    5
             mean   2025-01-10 04:48:00
             min    2025-01-03 00:00:00
             25%    2025-01-08 00:00:00
             50%    2025-01-11 00:00:00
             75%    2025-01-12 00:00:00
             max    2025-01-17 00:00:00
             std                    NaN

In [44]:
data.head()

   CustomerID Region     Product  Quantity  Price PurchaseDate
0        1007  North      Mobile         2    487   2025-01-01
1        1004   West      Tablet         1    101   2025-01-02
2        1008  South  Headphones         2    489   2025-01-03
3        1005  South      Tablet         1    665   2025-01-04
4        1007  North  Headphones         2    205   2025-01-05

In [46]:
data['CustomerID'].unique()

array([1007, 1004, 1008, 1005, 1003, 1006, 1002], dtype=int32)

In [47]:
data['CustomerID'].nunique()

7

In [48]:
data['CustomerID'].value_counts()

CustomerID
1008    5
1005    4
1007    3
1004    2
1003    2
1006    2
1002    2
Name: count, dtype: int64

In [49]:
def times2(x):
    return x*2

In [50]:
data['Price'].apply(times2)

0      974
1      202
2      978
3     1330
4      410
5     1742
6     1842
7     1152
8     1604
9     1002
10    1658
11    1310
12     522
13     602
14     738
15    1924
16    1830
17     740
18    1110
19    1122
Name: Price, dtype: int64

In [53]:
data.columns

Index(['CustomerID', 'Region', 'Product', 'Quantity', 'Price', 'PurchaseDate'], dtype='object')

In [54]:
data.index

RangeIndex(start=0, stop=20, step=1)

In [60]:
data.sort_values('Price')

    CustomerID Region     Product  Quantity  Price PurchaseDate
1         1004   West      Tablet         1    101   2025-01-02
4         1007  North  Headphones         2    205   2025-01-05
12        1003   West      Laptop         4    261   2025-01-13
13        1006   West      Tablet         3    301   2025-01-14
14        1005   West      Mobile         3    369   2025-01-15
17        1006  South  Headphones         4    370   2025-01-18
0         1007  North      Mobile         2    487   2025-01-01
2         1008  South  Headphones         2    489   2025-01-03
9         1004   East      Tablet         3    501   2025-01-10
18        1002  South      Mobile         2    555   2025-01-19
19        1005   East      Mobile         4    561   2025-01-20
7         1008  North      Tablet         3    576   2025-01-08
11        1008  South      Laptop         1    655   2025-01-12
3         1005  South      Tablet         1    665   2025-01-04
8         1005   East      Laptop         4    802   2025-01-09
10        1008   East      Tablet         4    829   2025-01-11
5         1003   West  Headphones         4    871   2025-01-06
16        1008   East      Laptop         1    915   2025-01-17
6         1007  North      Laptop         4    921   2025-01-07
15        1002   West  Headphones         2    962   2025-01-16

In [61]:
data.pivot_table(
    values=["Quantity", "Price"],
    index="Product",
    aggfunc={"Quantity": "sum", "Price": "mean"}
)

            Price  Quantity
Product
Headphones  579.4        14
Laptop      710.8        14
Mobile      493.0        11
Tablet      495.5        15